# -*- coding: utf-8 -*-
"""Assignment_1_Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbAdfjMdtYpJ6SBhIi6L_vMHF7yqfVi1

## 1. In the below elements which of them are values or an expression? eg:- values can be
integer or string and expressions will be mathematical operators.
*

&#39;hello&#39;

-87.8

-

/

+
6
"""



"""Expression: +, -, *, /
Values: 'hello', -88.5, 5

## 2. What is the difference between string and variable?
"""



"""VARIABLE:-Variables are symbols that you can use to store data in a program.You can think of them as an empty box that you fill with some data or value.
STRING:- Strings are data, so we can use them to fill up a variable

## 3. Describe three different data types.
"""

Integer	Whole numbers	7, 12, 999
Float (floating point)	Number with a decimal point	3.15, 9.06, 00.13
Character	Encoding text numerically	97 (in ASCII, 97 is a lower case 'a')
Boolean	Representing logical values	TRUE, FALSE

"""## 4. What is an expression made up of? What do all expressions do?"""

An expression is a construct made up of variables, operators,
and method invocations, which are constructed according to the syntax of the language,
that evaluates to a single value.

"""## 5. This assignment statements, like spam = 10. What is the difference between an expression and a statement?"""

an “expression” is a combination of values and functions that are combined and interpreted by the compiler to create a new value, as opposed to a “statement” which is just a standalone unit of execution and doesn't return anything.

"""## 6. After running the following code, what does the variable bacon contain?
bacon = 22

bacon + 1
"""

The bacon variable is set to 20. The bacon + 1 expression does not reassign the value in bacon
(that would need an assignment statement: bacon = bacon + 1)

bacon = 22
bacon = bacon + 1
print(bacon)

"""## 7. What should the values of the following two terms be?

&#39;spam&#39; + &#39;spamspam&#39;

&#39;spam&#39; * 3
"""

Both expressions evaluate to the string 'spamspamspam'

spam = ("spam" + "spamspam")
print(spam)

spam = ("spam" * 3)
print(spam)

"""## 8. Why is eggs a valid variable name while 100 is invalid?"""

Variable names cannot begin with a number.